baseurl: ""
url: "http://stress.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js

title: "Как избавиться от негативных эмоций, напряжения и стресса в бизнесе"
description: "Техники работы с внутренним состоянием, позволяющие меньше уставать и быстрее восстанавливаться. Как снять стресс после интенсивной рабочей недели эффективно и без бухла"
keywords: "стресс, бизнес, медитация, бодрость, хорошее настроение"
author: "Николай Воробьёв"

permalink: /:title/

vk_app_id: 5640654 # localhost:8000
yandex_metrika: 39943320 # stress.nickvorobiov.com
google_analytics: UA-46456269-18 # stress.nickvorobiov.com
